import sys
from dataclasses import dataclass, fields
import subprocess

version_file_suffix = sys.argv[1]


@dataclass
class Config:
    enable_chapters_from_sem1: bool = True
    enable_chapters_from_sem2: bool = True
    enable_unfinished_chapters: bool = False
    enable_ticket_references: bool = False
    monochrome: bool = False

    def write_to_file(self, file):
        file.write("// FIXME: This config is autogenerated and should not be committed!\n\n\n")

        for field in fields(self):
            typst_field_name = field.name.replace("_", "-")
            value = getattr(self, field.name)
            if isinstance(value, bool):
                value = "true" if value else "false"
            else:
                raise NotImplementedError(f"Unknown type for field {field.name}: {type(value)}")
            file.write(f"#let {typst_field_name} = {value}\n")


targets = {
    "algebra-all": Config(
        enable_chapters_from_sem1 = True,
        enable_chapters_from_sem2 = True,
        enable_unfinished_chapters = True,
        enable_ticket_references = False,
        monochrome = False,
    ),

    "algebra-sem1": Config(
        enable_chapters_from_sem1 = True,
        enable_chapters_from_sem2 = False,
        enable_unfinished_chapters = True,
        enable_ticket_references = False,
        monochrome = False,
    ),

    "algebra-sem2": Config(
        enable_chapters_from_sem1 = False,
        enable_chapters_from_sem2 = True,
        enable_unfinished_chapters = True,
        enable_ticket_references = False,
        monochrome = False,
    ),

    "algebra-all-with-tickets": Config(
        enable_chapters_from_sem1 = True,
        enable_chapters_from_sem2 = True,
        enable_unfinished_chapters = False,
        enable_ticket_references = True,
        monochrome = False,
    ),

    "algebra-sem1-with-tickets": Config(
        enable_chapters_from_sem1 = True,
        enable_chapters_from_sem2 = False,
        enable_unfinished_chapters = False,
        enable_ticket_references = True,
        monochrome = False,
    ),

    "algebra-sem2-with-tickets": Config(
        enable_chapters_from_sem1 = False,
        enable_chapters_from_sem2 = True,
        enable_unfinished_chapters = False,
        enable_ticket_references = True,
        monochrome = False,
    ),

    "algebra-all-with-tickets-monochrome": Config(
        enable_chapters_from_sem1 = True,
        enable_chapters_from_sem2 = True,
        enable_unfinished_chapters = False,
        enable_ticket_references = True,
        monochrome = True,
    ),

    "algebra-sem1-with-tickets-monochrome": Config(
        enable_chapters_from_sem1 = True,
        enable_chapters_from_sem2 = False,
        enable_unfinished_chapters = False,
        enable_ticket_references = True,
        monochrome = True,
    ),

    "algebra-sem2-with-tickets-monochrome": Config(
        enable_chapters_from_sem1 = False,
        enable_chapters_from_sem2 = True,
        enable_unfinished_chapters = False,
        enable_ticket_references = True,
        monochrome = True,
    ),
}

any_failed = False

with open("config.typ", "r") as config_file:
    initial_config = config_file.read()


for target, config in targets.items():
    with open("config.typ", "w") as config_file:
        config.write_to_file(config_file)
    
    result = subprocess.run(["typst", "compile", "main.typ", f"{target}.pdf"])

    if result.returncode != 0:
        print(f"Failed to compile {target}")
        any_failed = True

with open("config.typ", "w") as config_file:
    config_file.write(initial_config)


if any_failed:
    sys.exit(1)
