= Линейная алгебра

#include "1-permutations-cont.typ"
#include "2-determinants.typ"
#include "3-determinants-more-props.typ"
#include "4-linear-spaces.typ"
#include "5-linear-subspaces.typ"
#include "6-linear-dep-and-indep.typ"
#include "7-basis.typ"
#include "8-coords.typ"
#include "9-rank.typ"
#include "10-direct-sum.typ"
#include "11-linear-mappings.typ"
#include "12-linear-mapping-matrix.typ"
#include "13-linear-operators.typ"
#include "14-eigen-values-vectors.typ"
